### ISSUE TITLE
동물 예방접종 기록 버그

### ISSUE THREAD

**Issue by JYeonJun** [illdang100/molly#140]
동일한 날짜에 '종합 백신 1차', '종합 백신 2차', '종합 백신 3차' 등 여러 예방접종 등록시 계산 버그 발생
![image](https://github.com/illdang100/molly/assets/97449471/ccd44485-75ba-49c9-ade4-4d38f81c688e)
-> 2차 3차를 맞은 기록이 데이터베이스에 존재하지만 여전히 화면에 출력된다.

**Comment by wl2258** [comment]
원인: 종합백신의 경우 다른 차수를 같은 날짜에 맞는 경우를 전혀 고려하지 않고 구현을 했다. 그러나 이런 경우는 극히 드물다.
해결 방법: 이전 기록을 저장한 배열 정렬을 오름차순으로 변경해서 가장 마지막 원소(가장 최근 접종)를 기준으로 다음 예방접종 날짜를 예측해 계산하도록 했다.
