### ISSUE TITLE
리프래시 토큰 에러

### ISSUE THREAD

**Issue by JYeonJun** [illdang100/molly#44]
상황: 액세스 토큰 만료를 가정하고 회원가입 후 닉네임 중복검사 실시
-> 서버에서 HttpServletResponse 객체가 두 번 호출됨.
-> 리액트에서 서버로 토큰 재발급 요청이 무한해서 발생함.

상황: 회원가입 후
-> 로컬 스토리지에 토큰이 저장되었지만 배너 페이지에 로그인 버튼이 로그아웃 버튼으로 변경되지 않음.

**Comment by yunzung** [comment]
해결 : 액세스 토큰 만료를 가정하고 회원가입 후 닉네임 중복검사 실시

fetch 를 사용해 중복검사 api 요청 후 토큰이 만료됐다는 상태코드가 오면 refreshToken으로 Jwt 토큰을 재발급 받는 api 요청을 시도함.
재발급 받는 것은 정상적으로 수행되었으나 재발급 된 토큰으로 기존 request를 재시도 하는 것에 어려움이 있었음. ( 기존 request 를 요청하는 함수를 호출한 후 토큰 재발급 요청 무한 발생 )
-> axios 로 HTTP 클라이언트 변경. axios 요청이 then으로 넘어가기 전 request, response를 가로채 작업할 수 있는 interceptor 사용
-> response에서 error가 발생했을 경우 catch로 넘어가기 전에 토큰 만료를 검사함. 상태코드를 통해 토큰이 만료됐음을 확인하면 resfresh 토큰을 사용해 토큰 재발급 api 요청. 새로 발급 받은 토큰으로 기존 실패했던 request 재요청함.
-> 인증실패 에러 발생. 
->  기존 request에서 헤더로 보낸 토큰이 서버로 전송되지 않음을 확인. 이유는 axios.post() 에서 parameter가 url, data, config 순이라서 헤더를 바디 뒷 순서에 넣어야했음. 
-> 토큰 재발급은 잘 되었으나 validation 에러 발생
-> 이유는 기존 request에서 body가 JSON 객체 형식으로 되어있지 않아서 였음. 수정 후 토큰 재발급 및 기존 request 요청 정상 수행됨.
-> 재발급 된 토큰이 localStorage에 저장되지 않음을 확인. 이유는 소셜로그인 후 토큰을 url 파라미터로 받는데 코드 맨 윗줄에 파라미터를 추출해 해당 토큰을 저장해놔서 리로드 될 때마다 이전 토큰이 계속 localStorage에 저장되었음. 
-> useEffect 를 사용해 맨처음 리로드 될 때만 url 파라미터로 받은 토큰을 저장하도록 하였음.

해결 : 로그인 버튼이 로그아웃 버튼으로 변경되지 않음.

localStorage에 토큰이 있으면 로그아웃, 없으면 로그인을 표시하는데 useState를 사용해 로그아웃을 누를 때 바로 반영될 수 있도록 함. 
처음 url 파라미터로 받은 토큰이 리로드 될 때마다 계속 localStorage에 저장되기 때문에 ui 상 문제가 있었음. useEffect를 사용해 처음 리로드 될 때만 url 파라미터로 받은 토큰을 저장하고, 이후 로그아웃을 누르면 localStorage에 있는 값을 모두 삭제하도록 함.
