### ISSUE TITLE
로그인 후 로그인 버튼이 로그아웃 버튼으로 변경되지 않는 오류

### ISSUE THREAD

**Issue by JYeonJun** [illdang100/molly#48]
![image](https://user-images.githubusercontent.com/97449471/230730892-2974e788-b63b-495a-9daf-437b1aa1417e.png)

**Comment by yunzung** [comment]
해결 : 사용자가 회원가입일 경우 소셜로그인 절차 후 토큰을 발급받아 localStorage에 저장된 채로 첫페이지에 redirect된다. 기존 회원인 사용자가 로그인을 할 경우에는 url 파라미터에 토큰이 포함된 채로 첫페이지에 redirect 된다. 따라서 두 경우를 분리하여 코드를 수정하였다. 
페이지가 리로드 될 때마다 localStorage에 계속 저장되는 것을 막기 위해 useEffect로 첫 리로드 될 경우로 지정해준다.  로그인 여부는 useState로 관리해준다. url 파라미터에 토큰이 있을 경우에는 localStorage에 저장한 후 로그인 여부를 true 로 바꿔주고, 사용자가 회원가입 후 리다이렉트 된 경우에는 localStorage에 이미 값이 있으므로 localStorage.getItem()을 사용해 토큰이 있으면 로그인 여부를 true로 바꿔준다.
로그인 여부가 true가 되면 ui에 로그아웃으로 바뀌고, 로그아웃을 클릭하면 localStorage에 있는 토큰을 지운 후 로그인 여부를 false로 바꿔준다.
